 - hosts: all
   user: vagrant
   become: yes
   become_method: sudo
   tasks:
    - name: Added variables
      include_vars:
        file: ../vars/vars.yml

    - name: Find if admin user already created
      command: /opt/mattermost/bin/mattermost user search {{admin_email}}
      register: admin_user
      become: true
      
    - name: Create admin user if there isn't already one
      command: /opt/mattermost/bin/mattermost user create --email {{admin_email}} --username {{admin_name}} --password Password --system_admin
      no_log: true
      become: true
      when: admin_user.stderr_lines|length == 1

    - name: Find if a team has been created
      command: /opt/mattermost/bin/mattermost team list
      register: first_team
      become: true

    - block:
      - name: Create a team if there isn't one.
        command: /opt/mattermost/bin/mattermost team create --name {{team_name}} --display_name devops --private --email {{admin_email}} 
        become: true

      - name: Add admin to the created team.
        command: /opt/mattermost/bin/mattermost team add {{team_name}}  {{admin_email}}  {{admin_name}}
        become: true
      when: first_team.stderr_lines|length == 0