 - hosts: all
   user: vagrant
   become: yes
   become_method: sudo
   tasks:
    - name: Added variables
      include_vars:
        file: ../vars/vars.yml
        
    - name: Creating first team "DevOps"
      shell: sudo -u mattermost ./mattermost team create --name {{team_name}} --display_name "{{team_name}} Team"
      args:
        chdir: /opt/mattermost/bin

    - name: Creating an admin account
      shell: sudo -u mattermost ./mattermost user create --email admin@example.com --username {{admin_name}} --password Password
      args:
        chdir: /opt/mattermost/bin

    - name: Creating a user account
      shell: sudo -u mattermost ./mattermost user create --email user@example.com --username {{user_name}} --password Password
      args:
        chdir: /opt/mattermost/bin

    - name: Adding user and admin to the team
      shell: sudo -u mattermost ./mattermost team add {{team_name}} {{admin_name}} {{user_name}}
      args:
        chdir: /opt/mattermost/bin

