- hosts: all
  user: vagrant
  become: yes
  become_method: sudo

  tasks:

    - name: Added variables
      include_vars:
        file: ../vars/vars.yml
    
    - name: copy .my.cnf file with root password credentials
      template:
        src: ./.my.cnf
        dest: ~/.my.cnf
        owner: root
        mode: 0600

    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value="{{mysql_root_pass}}"  vtype='password'
     
    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value="{{mysql_root_pass}}" vtype='password'

    - name: Install mysql-server bindings
      apt: name=mysql-server state=present
      become: yes
      become_method: sudo

    - name: Install base packages
      apt: name={{ item }} state=present
      with_items:
        - python-pip
        - python3-pip
        - jq
      tags:
        - packages

    - name: Install pymysql-server bindings
      apt: name=python3-pymysql state=present
      become: yes
      become_method: sudo

    - name: install python-mysql-server bindings
      apt: name=python-mysqldb state=present
      become: yes
      become_method: sudo

    - name: Start the MySQL service
      sudo: yes
      service:
        name: mysql
        state: started
        enabled: true
        
    - name: Creating a user
      sudo: yes
      mysql_user:
        name: "{{mysql_user}}"
        password: "{{mysql_password}}"
        priv: '*.*:ALL'
        state: present


    - name: Create a new database 'mattermost'
      mysql_db:
        name: mattermost
        state: present
